# Generated by Django 4.0.4 on 2022-06-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_infos', '0002_alter_personalinfo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(max_length=100)),
                ('builded_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='copyright_text',
        ),
    ]
