# Generated by Django 4.0.4 on 2022-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_infos', '0003_sitesettings_remove_personalinfo_copyright_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
