# Generated by Django 4.0.4 on 2022-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_infos', '0004_sitesettings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='persian_name',
            field=models.CharField(default='رضا رضایی', max_length=30, verbose_name='نام خود را به فارسی وارد کنید'),
            preserve_default=False,
        ),
    ]
