# Generated by Django 4.0.4 on 2022-06-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_infos', '0005_personalinfo_persian_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='profile',
            new_name='profile_image',
        ),
    ]
