# Generated by Django 4.0.4 on 2022-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_infos', '0006_rename_profile_personalinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
