# Generated by Django 4.0.4 on 2022-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbadge',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestgroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
