# Generated by Django 4.0.4 on 2022-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_interestbadge_is_active_interestgroup_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestbadge',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
