# Generated by Django 4.0.4 on 2022-05-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_alter_interestbadge_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestbadge',
            name='description',
            field=models.CharField(max_length=50, verbose_name='A short description for this badge'),
        ),
        migrations.AlterField(
            model_name='interestbadge',
            name='name',
            field=models.CharField(max_length=25, verbose_name='badge name'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='description',
            field=models.CharField(max_length=50, verbose_name='A short description for this badge'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='name',
            field=models.CharField(max_length=25, verbose_name='badge name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=50, verbose_name='A short description for this badge'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=25, verbose_name='badge name'),
        ),
    ]
