# Generated by Django 4.0.4 on 2022-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_alter_interestbadge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestbadge',
            name='description_link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='description_link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description_link',
            field=models.URLField(default='#'),
        ),
    ]
