# Generated by Django 4.0.4 on 2022-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_alter_experience_related_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='related_website',
            field=models.URLField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='interestbadge',
            name='description_link',
            field=models.URLField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='description_link',
            field=models.URLField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description_link',
            field=models.URLField(blank=1, null=1),
        ),
    ]
