# Generated by Django 4.0.4 on 2022-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_alter_experience_related_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestbadge',
            name='description',
            field=models.CharField(blank=1, max_length=50, null=1, verbose_name='A short description for this badge'),
        ),
        migrations.AlterField(
            model_name='interestgroup',
            name='description',
            field=models.CharField(blank=1, max_length=50, null=1, verbose_name='A short description for this badge'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=1, max_length=50, null=1, verbose_name='A short description for this badge'),
        ),
    ]
