# Generated by Django 4.0.4 on 2022-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_alter_interestbadge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
