# Generated by Django 4.0.4 on 2022-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0010_experience_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestgroup',
            name='description_link',
        ),
    ]
