# Generated by Django 4.0.4 on 2022-06-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0011_remove_interestgroup_description_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbadge',
            name='order',
            field=models.SmallIntegerField(blank=1, default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.SmallIntegerField(blank=1, default=1),
        ),
    ]
